version: 2.1

jobs:
  run_tests:
    docker:
      - image: node:21.6.1-alpine

    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - store_test_results:
          path: test-results

workflows:
  test:
    jobs:
      - run_tests