version: 2.1

jobs:
  run_tests:
    docker:
      - image: node:21.6.1-alpine

    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - run_tests